name: Pull Docker Image

on:
  workflow_dispatch:

jobs:
  pull-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Pull image
        run: docker pull markoshust/magento-php:8.3-fpm-4

      - name: Save image to tar
        run: docker save markoshust/magento-php:8.3-fpm-4 -o magento.tar

      - name: Compress (optional)
        run: gzip magento.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: magento-image
          path: magento.tar.gz