name: Sync Docker Image to ACR

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Pull image from Docker Hub
        run: |
          docker pull markoshust/magento-php:8.3-fpm-4

      - name: Login to Aliyun ACR
        run: |
          echo "${{ secrets.ALI_PASSWORD }}" | docker login ${{ secrets.ALI_REGISTRY }} \
          -u "${{ secrets.ALI_USERNAME }}" \
          --password-stdin

      - name: Tag image
        run: |
          docker tag markoshust/magento-php:8.3-fpm-4 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/magento-php:8.3-fpm-4

      - name: Push to ACR
        run: |
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/magento-php:8.3-fpm-4